<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareLibre [
<!ELEMENT softwareLibre (programas,licencias)>
<!ELEMENT programas (programa*)>
<!ELEMENT programa (nombre,version*)>
<!ELEMENT licencias (licencia*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT licencia EMPTY>
<!ELEMENT version EMPTY>

<!ATTLIST licencia id ID #REQUIRED>
<!ATTLIST version id CDATA #REQUIRED>
<!ATTLIST version licencia CDATA #REQUIRED>
<!ATTLIST version fechapublicacion CDATA #IMPLIED>
]>

<softwareLibre>
    <programas>
        <programa>
            <nombre>Inkscape</nombre>
            <version id="0.47" licencia="GPLv2" fechapublicacion="17/08/2010" />
            <version id="0.48" licencia="GPLv2" fechapublicacion="17/08/2010" />
            <version id="0.48.2" licencia="GPLv2" fechapublicacion="14/08/2011" />
        </programa>
        <programa>
            <nombre>PostgreSQL</nombre>
            <version id="9.1.0" licencia="BSD2" fechapublicacion="15/09/2011" />
            <version id="9.1.3" licencia="BSD2"/>
        </programa>
    </programas>
    <licencias>
        <licencia id="GPLv2" />
        <licencia id="BSD2" />
        <licencia id="Apachev2" />
</licencias>
</softwareLibre>