<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera [
<!ELEMENT cartelera (peliculas*,cines*)>
<!ELEMENT peliculas (pelicula*)>
<!ELEMENT cines (cine*)>
<!ELEMENT pelicula (#PCDATA)>
<!ELEMENT cine (#PCDATA)>

<!ATTLIST pelicula titulo CDATA #REQUIRED>
<!ATTLIST pelicula ano CDATA #REQUIRED>
<!ATTLIST pelicula director CDATA #REQUIRED>
<!ATTLIST pelicula identificador CDATA #REQUIRED>

<!ATTLIST cine nombre CDATA #REQUIRED>
<!ATTLIST cine sala CDATA #REQUIRED>
<!ATTLIST cine identificador CDATA #REQUIRED>
<!ATTLIST cine sesion CDATA #REQUIRED>

]>
<cartelera>
    <peliculas>
        <pelicula titulo="La invenciÃ³n de Hugo" ano="2011" director="Martin Scorsese" identificador="1"></pelicula>
        <pelicula titulo="John Carter" ano="2012" director="Andrew Stanton" identificador="2"></pelicula>
        <pelicula titulo="Intocable" ano="2012" director="Olivier Nakache" identificador="3"></pelicula>
    </peliculas>
    <cines>
        <cine nombre="ABC El Saler" sala="Sala 6" identificador="1" sesion="18:00 20:25 22:50"></cine>
        <cine nombre="Lys" sala="Sala 3" identificador="2" sesion="16:20 18:50"></cine>
    </cines>
</cartelera>